name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.6"
          - "8.8"
          - "8.10"
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
          - "9.10"
          - "9.12"
        include:
        - os: macOS-latest
          ghc: "9.12"
        - os: windows-latest
          ghc: "9.12"
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true

    - uses: actions/cache@v4
      name: Cache cabal store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Cabal version
      run: |
        cabal --version

    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get directory-ospath-streaming-*.tar.gz

    - name: Build & Test
      run: |
        cd ../directory-ospath-streaming-*/
        cabal build all
        cabal test --test-show-details=direct all

    - name: Haddock
      run: |
        cd ../directory-ospath-streaming-*/
        cabal haddock all

    - name: Cabal check
      run: |
        cd ../directory-ospath-streaming-*/
        cabal check

    - name: Build & Test unix < 2.8.6
      if: matrix.ghc == '8.6' || matrix.ghc == '8.8'  || matrix.ghc == '8.10' || matrix.ghc == '8.10' || matrix.ghc == '9.2' || matrix.ghc == '9.4' || matrix.ghc == '9.6' || matrix.ghc == '9.8' || matrix.ghc == '9.10'
      run: |
        cd ../directory-ospath-streaming-*/
        cabal build --constraint 'unix < 2.8.6' all
        cabal test --constraint 'unix < 2.8.6' --test-show-details=direct all

    - name: Build & Test unix >= 2.8.6
      run: |
        cd ../directory-ospath-streaming-*/
        cabal build --constraint 'unix >= 2.8.6' all
        cabal test --constraint 'unix >= 2.8.6' --test-show-details=direct all

  emulated:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['armv7', 'aarch64']
    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v2
      timeout-minutes: 60
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu_rolling
        githubToken: ${{ github.token }}
        install: |
          apt-get update -y
          apt-get install -y curl ghc cabal-install libghc-tasty-quickcheck-dev libghc-tasty-hunit-dev
        run: |
          cabal update
          cabal build all
          cabal test --test-show-details=direct all
