name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
        include:
        - os: macOS-latest
          ghc: "9.8"
        - os: windows-latest
          ghc: "9.8"
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true
    - uses: actions/cache@v3
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Cabal version
      run: |
        cabal --version
    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get directory-ospath-streaming-*.tar.gz

    - name: Build & Test default
      run: |
        cd ../directory-ospath-streaming-*/
        cabal build all
        cabal test --test-show-details=direct all
    - name: Haddock
      run: |
        cd ../directory-ospath-streaming-*/
        cabal haddock all
    - name: Cabal check
      run: |
        cd ../directory-ospath-streaming-*/
        cabal check
